### ISSUE TITLE
Support app.config.js and app.config.ts

### ISSUE THREAD

**Issue by crutch12** [meecodebymariomurrent/eas-build-notifier#1]
Docs:
https://docs.expo.dev/workflow/configuration/#using-typescript-for-configuration-appconfigts-instead-of

We should support it. Maybe there is a way to read final .json from env

Also:
> This lib is awesome!

**Comment by mariomurrent-softwaresolutions** [comment]
Hi, thank you for contributing. I will have a look at it today or tomorrow :)

**Comment by mariomurrent-softwaresolutions** [comment]
New version release. Thank you very much for contributing.
